[pytest]
testpaths = tests
python_files = test_*.py
addopts = -q
asyncio_default_fixture_loop_scope = function
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning
    ignore::pytest.PytestDeprecationWarning
